[package]
name = "editor-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
memchr = "2.8.0"
io = { path = "../io" }

[dev-dependencies]
tempfile = { workspace = true }
