[package]
name = "layout"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
editor-core = { path = "../editor-core" }
editor-state = { path = "../editor-state" }
fltk = { workspace = true }
